
export default class ActivePaymentConstants
{
  static DEPOSIT_PAYMENT = 3001;
  static DEPOSIT_REFUND = 3002;
  static COUPON_PAYMENT = 3003;
  static DIVIDEND_PAYMENT = 3004;
  static CREDIT_PAYMENT = 3005;
  static CLOSE_INSURANCE_PAYMENT = 3006;
  static INSURANCE_PAYMENT_RENT = 3007;
  static CLOSE_INSURANCE_PAYMENT_RENT = 3008;
  static INSURANCE_PAYMENT = 3009;
}